[project]
name = "pythonaiimagechecker"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "opencv-python>=4.12.0.88",
    "streamlit>=1.47.1",
    "tensorflow>=2.15.0",
    "tensorflow-io-gcs-filesystem==0.31.0",
]
